//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsToday_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity_counts
    {
        public int PK_Activity { get; set; }
        public Nullable<int> UrlTotal_Today { get; set; }
        public Nullable<int> UrlPercent_Today { get; set; }
        public Nullable<int> VisitsTotal_Today { get; set; }
        public Nullable<int> VisitsPercent_Today { get; set; }
        public Nullable<int> RevisitsTotal_Today { get; set; }
        public Nullable<int> RevisitsPercent_Today { get; set; }
        public Nullable<int> NoVisitsTotal_Today { get; set; }
        public Nullable<int> NoVisitsPercent_Today { get; set; }
        public Nullable<int> UrlTotal_Week { get; set; }
        public Nullable<int> UrlPercent_Week { get; set; }
        public Nullable<int> VisitsTotal_Week { get; set; }
        public Nullable<int> VisitsPercent_Week { get; set; }
        public Nullable<int> RevisitsTotal_Week { get; set; }
        public Nullable<int> RevisitsPercent_Week { get; set; }
        public Nullable<int> NoVisitsTotal_Week { get; set; }
        public Nullable<int> NoVisitsPercent_Week { get; set; }
        public Nullable<int> UrlTotal_Month { get; set; }
        public Nullable<int> UrlPercent_Month { get; set; }
        public Nullable<int> VisitsTotal_Month { get; set; }
        public Nullable<int> VisitsPercent_Month { get; set; }
        public Nullable<int> RevisitsTotal_Month { get; set; }
        public Nullable<int> RevisitsPercent_Month { get; set; }
        public Nullable<int> NoVisitsTotal_Month { get; set; }
        public Nullable<int> NoVisitsPercent_Month { get; set; }
        public Nullable<int> DaysCount { get; set; }
        public Nullable<int> FK_Rid { get; set; }
        public Nullable<int> FK_ClientId { get; set; }
    }
}
