//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsToday_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class excluded_shorturl
    {
        public int PK_Exclude_Shorturl { get; set; }
        public string Ipv4 { get; set; }
        public string Ipv6 { get; set; }
        public string Browser { get; set; }
        public string Browser_version { get; set; }
        public string Req_url { get; set; }
        public string UserAgent { get; set; }
        public string IsMobileDevice { get; set; }
        public string HeaderValues { get; set; }
        public Nullable<int> FK_Uid { get; set; }
        public Nullable<int> FK_RID { get; set; }
        public Nullable<int> FK_ClientID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
