//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsToday_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class messagelink
    {
        public int PK_LinkID { get; set; }
        public Nullable<int> ShortUrlId { get; set; }
        public string LinkTag { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
