//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsToday_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class shorturlclickreference
    {
        public int PK_ClickID { get; set; }
        public Nullable<int> Ref_ShorturlClickID { get; set; }
        public Nullable<int> Ref_UsersID { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
