//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsToday_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class stat_counts
    {
        public int PK_Stat { get; set; }
        public Nullable<int> TotalUsers { get; set; }
        public Nullable<int> UniqueUsers { get; set; }
        public Nullable<int> UniqueUsersToday { get; set; }
        public Nullable<int> UsersToday { get; set; }
        public Nullable<int> UniqueUsersYesterday { get; set; }
        public Nullable<int> UsersYesterday { get; set; }
        public Nullable<int> UniqueUsersLast7days { get; set; }
        public Nullable<int> UsersLast7days { get; set; }
        public Nullable<int> TotalVisits { get; set; }
        public Nullable<int> VisitsToday { get; set; }
        public Nullable<int> UniqueVisitsToday { get; set; }
        public Nullable<int> VisitsYesterday { get; set; }
        public Nullable<int> UniqueVisitsYesterday { get; set; }
        public Nullable<int> UniqueVisitsLast7day { get; set; }
        public Nullable<int> VisitsLast7days { get; set; }
        public Nullable<int> TotalCamapigns { get; set; }
        public Nullable<int> CampaignsLast7days { get; set; }
        public Nullable<int> CampaignsMonth { get; set; }
        public Nullable<int> UrlTotal_Today { get; set; }
        public Nullable<double> UrlPercent_Today { get; set; }
        public Nullable<int> VisitsTotal_Today { get; set; }
        public Nullable<double> VisitsPercent_Today { get; set; }
        public Nullable<int> RevisitsTotal_Today { get; set; }
        public Nullable<double> RevisitsPercent_Today { get; set; }
        public Nullable<int> NoVisitsTotal_Today { get; set; }
        public Nullable<double> NoVisitsPercent_Today { get; set; }
        public Nullable<int> UrlTotal_Week { get; set; }
        public Nullable<double> UrlPercent_Week { get; set; }
        public Nullable<int> VisitsTotal_Week { get; set; }
        public Nullable<double> VisitsPercent_Week { get; set; }
        public Nullable<int> RevisitsTotal_Week { get; set; }
        public Nullable<double> RevisitsPercent_Week { get; set; }
        public Nullable<int> NoVisitsTotal_Week { get; set; }
        public Nullable<double> NoVisitsPercent_Week { get; set; }
        public Nullable<int> UrlTotal_Month { get; set; }
        public Nullable<double> UrlTotalPercent_Month { get; set; }
        public Nullable<int> VisitsTotal_Month { get; set; }
        public Nullable<double> VisitsPercent_Month { get; set; }
        public Nullable<int> RevisitsTotal_Month { get; set; }
        public Nullable<double> RevisitsPercent_Month { get; set; }
        public Nullable<int> NoVisitsTotal_Month { get; set; }
        public Nullable<double> NoVisitsPercent_Month { get; set; }
        public Nullable<int> DaysCount_Week { get; set; }
        public Nullable<int> DaysCount_Month { get; set; }
        public Nullable<int> FK_Rid { get; set; }
        public Nullable<int> FK_ClientID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UniqueVisits { get; set; }
        public Nullable<int> RevisitsTotal_Yesterday { get; set; }
        public Nullable<int> NoVisitsTotal_Yesterday { get; set; }
    }
}
