//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsToday_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class stats_counts_today
    {
        public int PKStatsToday_Count { get; set; }
        public Nullable<int> Users_Today { get; set; }
        public Nullable<int> Visits_Today { get; set; }
        public Nullable<int> Revisitsl_Today { get; set; }
        public Nullable<int> NoVisits_Today { get; set; }
        public Nullable<int> UniqueUsers_Today { get; set; }
        public Nullable<int> UniqueVisits_Today { get; set; }
        public Nullable<int> FK_RID { get; set; }
        public Nullable<int> FK_ClientID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual client client { get; set; }
        public virtual riddata riddata { get; set; }
    }
}
