//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsToday_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class uiddata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uiddata()
        {
            this.shorturldatas = new HashSet<shorturldata>();
        }
    
        public int PK_Uid { get; set; }
        public Nullable<int> FK_RID { get; set; }
        public Nullable<int> FK_ClientID { get; set; }
        public string ReferenceNumber { get; set; }
        public string LongurlorMessage { get; set; }
        public string MobileNumber { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UniqueNumber { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> FK_Batchid { get; set; }
        public string ExistingUrlBatchIds { get; set; }
    
        public virtual client client { get; set; }
        public virtual riddata riddata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shorturldata> shorturldatas { get; set; }
    }
}
